language: java

jdk:
  - openjdk8

deploy:
  provider: releases
  api_key: "$GITHUB_UPLOAD_KEY"
  file_glob: true
  file:
    - upload/Jubler-*
  draft: true


before_install:
 - sudo apt-get update -y ; sudo apt-get install -y xmlto
 - ./resources/help/create
 - ./resources/i18n/compile

script:
 - set -e
 - mkdir uplaod
 - mvn clean install -Pdist-generic && cp modules/installer/target/Jubler-*tar.bz2 upload
 - mvn clean install -Pdist-linux && cp modules/installer/target/Jubler-*.appimage upload
 - mvn clean install -Pdist-osx && cp modules/installer/target/Jubler-*.appimage upload
 - mvn clean install -Pdist-windows && cp modules/installer/target/Jubler-*.appimage upload
