jobs:
  include:
    - os: linux
      language: java
      jdk: openjdk14
    - os: osx
      osx_image: xcode11.5
      language: java

addons:
  apt:
    packages:
      - ant
      - osslsigncode
  homebrew:
    packages:
      - ant
      - maven

deploy:
  provider: releases
  api_key: "$GITHUB_UPLOAD_KEY"
  file_glob: true
  skip_cleanup: true
  prerelease: true
  file:
    - upload/Jubler-*
  on:
    tags: true
  name: Prerelease - use it at your own risk
#  draft: true

before_install:
 - set -e ; mkdir upload
 - if [ $TRAVIS_OS_NAME = osx   ] ; then echo $P12_APPLE_CONTENT | base64 --decode > apple-keysign.p12 ; security create-keychain -p $P12_APPLE_PASS build.keychain ; security default-keychain -s build.keychain ; security unlock-keychain -p $P12_APPLE_PASS build.keychain ; security import apple-keysign.p12 -k build.keychain -P $P12_APPLE_PASS -T /usr/bin/codesign ; security find-identity -v ; security set-key-partition-list -S 'apple-tool:,apple:' -s -k $P12_APPLE_PASS build.keychain ; rm apple-keysign.p12 ; fi
 - if [ $TRAVIS_OS_NAME = linux ] ; then echo $P12_CONTENT | base64 --decode > modules/installer/secret/code-signing.p12 ; fi

script:
 - java -version
 - if [ $TRAVIS_OS_NAME = osx   ] ; then mvn clean && mvn install -Pdist-osx,notarize && cp modules/installer/target/Jubler-*.dmg upload/      ; fi
 - if [ $TRAVIS_OS_NAME = linux ] ; then mvn clean && mvn install -Pdist-generic      && cp modules/installer/target/Jubler-*tar.bz2 upload/   ; fi
 - if [ $TRAVIS_OS_NAME = linux ] ; then mvn clean && mvn install -Pdist-linux        && cp modules/installer/target/Jubler-*.appimage upload/ ; fi
 - if [ $TRAVIS_OS_NAME = linux ] ; then mvn clean && mvn install -Pdist-windows      && cp modules/installer/target/Jubler-*.exe upload/      ; fi
